/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse223.quoridor;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

import ca.mcgill.ecse223.quoridor.QuoridorApplication;


public class QuoridorTest {
    @Test public void testSomeLibraryMethod() {
        QuoridorApplication classUnderTest = new QuoridorApplication();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
