/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ecse223.project.group;

import org.junit.Test;

import ca.mcgill.ecse223.quoridor.QuoridorApplication;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        QuoridorApplication classUnderTest = new QuoridorApplication();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
